LOAD DATA INFILE './song_entries.csv'
INTO TABLE SONG
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

LOAD DATA INFILE './artist_entries.csv'
INTO TABLE ARTIST
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

LOAD DATA INFILE './album_entries.csv'
INTO TABLE ALBUM
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

LOAD DATA INFILE './language_entries.csv'
INTO TABLE LANGUAGE
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';

LOAD DATA INFILE './file_entries.csv'
INTO TABLE FILE
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n';